DROP TABLE IF EXISTS WeatherPredictions;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS logRegress;


CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE WeatherPredictions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date_made TEXT NOT NULL,
  guess_made TEXT NOT NULL);

  CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

  CREATE TABLE logRegress (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  num1 INTEGER NOT NULL,
  num2 INTEGER NOT NULL,
  num3 INTEGER NOT NULL,
  appleOrOrange TEXT NOT NULL
);
